version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: nextjs_seo_admin_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: seo_admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    command: 
      # PostgreSQL configuration for memory and bin log caching
      - "postgres"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "work_mem=8MB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "wal_buffers=4MB" # similar purpose to bin_log cache in MySQL
      - "-c"
      - "effective_cache_size=384MB"

volumes:
  pgdata:
